/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Conexion.Conexion;
import ConsultasSQL.QuerysVentas;
import Controlador.Clientes;
import Controlador.VentasServicios;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 * Nombre del archivo: CrearVentaServicio.java
 * Autor: Alejandra Suárez
 * Fecha de creación: [20/09/2023]
 * Descripción: JFRame que contiene los campos necesarios para agregar una nueva venta de servicio.
 * Derechos de autor (c) [20/09/2023] Alejandra Suárez. Todos los derechos reservados.
 */
public class CrearVentaServicio extends javax.swing.JFrame {

    public static int cliente = 0;
    private static Conexion con = new Conexion();
    private static java.sql.Connection conexion = con.getConexion();
    private static PreparedStatement ps = null;

    /**
     * Creates new form CrearVentaServicio
     */
    public CrearVentaServicio() {
        initComponents();
        // Genera un número de factura y un código hexadecimal para el CAI
        txtNumFactura.setText(generarNumeroFactura());
        txtCai.setText(generarCodigoHexadecimal());

        // Obtiene la fecha actual
        Date fechaActual = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");

        // Formatea la fecha utilizando el objeto SimpleDateFormat
        String fechaFormateada = formatoFecha.format(fechaActual);
        jlFecha.setText(fechaFormateada);

        // Establece un texto de ayuda para el campo jtClientes
        PromptSupport.setPrompt("Dar click para seleccionar cliente", jtClientes);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnManicura = new javax.swing.JButton();
        btntratamiento = new javax.swing.JButton();
        btnCorte = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicio = new javax.swing.JTable();
        jtClientes = new javax.swing.JTextField();
        txtCai = new javax.swing.JLabel();
        txtNumFactura = new javax.swing.JLabel();
        jlFecha = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 254));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Agregar venta de servicios");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Servicio:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Cliente:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Valor:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Fecha:");

        jButton1.setBackground(new java.awt.Color(255, 255, 254));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 254));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnManicura.setText("Manicura");
        btnManicura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManicuraActionPerformed(evt);
            }
        });

        btntratamiento.setText("Tratamientos");
        btntratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntratamientoActionPerformed(evt);
            }
        });

        btnCorte.setText("Tipos de cortes");
        btnCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("CAI:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Número de factura:");

        tblServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Núm.", "Descrpción", "Precio", "idCorte", "tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblServicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblServicioPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblServicio);
        if (tblServicio.getColumnModel().getColumnCount() > 0) {
            tblServicio.getColumnModel().getColumn(3).setMinWidth(0);
            tblServicio.getColumnModel().getColumn(3).setMaxWidth(0);
            tblServicio.getColumnModel().getColumn(4).setMinWidth(0);
            tblServicio.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        jtClientes.setEditable(false);
        jtClientes.setBackground(new java.awt.Color(255, 255, 254));
        jtClientes.setFocusable(false);
        jtClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtClientesMouseClicked(evt);
            }
        });
        jtClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtClientesActionPerformed(evt);
            }
        });

        txtCai.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtCai.setText("CAI");
        txtCai.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtNumFactura.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNumFactura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtNumFactura.setText("001-002-00-00000020");

        jlFecha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlFecha.setText("Fecha:");

        jlTotal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jlTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlTotal.setText("0.00");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ListaodologoBarberia (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumFactura)
                            .addComponent(txtCai))
                        .addGap(141, 213, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1))
                            .addComponent(jlFecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnManicura)
                        .addGap(25, 25, 25)
                        .addComponent(btntratamiento)
                        .addGap(18, 18, 18)
                        .addComponent(btnCorte)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlTotal))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(218, 218, 218)
                            .addComponent(jButton2))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnManicura)
                            .addComponent(btntratamiento)
                            .addComponent(btnCorte))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jlFecha))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCai))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Metodo para hacer visible la ventana de agregar corte
    private void btnCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorteActionPerformed
        ServicioCorte servicioCorte = new ServicioCorte();
        servicioCorte.setVisible(true);
        servicioCorte.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCorteActionPerformed
    // Metodo para hacer visible la ventana de agregar cliente
    private void jtClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtClientesMouseClicked
        CrearVentasServiciosClientes crearVentaServicio = new CrearVentasServiciosClientes();
        crearVentaServicio.setVisible(true);
        crearVentaServicio.setLocationRelativeTo(null);
    }//GEN-LAST:event_jtClientesMouseClicked

    private void jtClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtClientesActionPerformed

    }//GEN-LAST:event_jtClientesActionPerformed
    // Metodo para hacer visible la ventana de agregar manicura
    private void btnManicuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManicuraActionPerformed
        ServicioManicurayPedicura servicioManicurayPedicura = new ServicioManicurayPedicura();
        servicioManicurayPedicura.setVisible(true);
        servicioManicurayPedicura.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnManicuraActionPerformed

    private void tblServicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblServicioPropertyChange

    }//GEN-LAST:event_tblServicioPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // Verifica si no se ha seleccionado un cliente para la venta
        if (jtClientes.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un cliente para la venta");
            return;
        }

        // Configuración de los botones del cuadro de diálogo
        UIManager.put("OptionPane.yesButtonText", "Si");
        UIManager.put("OptionPane.noButtonText", "No");
        UIManager.put("OptionPane.cancelButtonText", "Cancelar");

        // Muestra un cuadro de confirmación para guardar la venta
        int decision = JOptionPane.showConfirmDialog(null, "Desea guardar esta venta", "", JOptionPane.WARNING_MESSAGE);
        if (decision == JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) tblServicio.getModel();
            // Verifica si hay detalles para la venta en la tabla
            if (model.getRowCount() > 0) {
                QuerysVentas ventas = new QuerysVentas();
                ventas.setCai(txtCai.getText());
                ventas.setFecha(jlFecha.getText());
                ventas.setNumeroFactura(txtNumFactura.getText());
                ventas.setFk_cliente(CrearVentaServicio.cliente);
                ventas.setImpuestos(0.00);
                ventas.setTotal(Double.valueOf(jlTotal.getText().replace(',', '.')));

                // Guarda la venta en la base de datos
                VentasServicios.Guardar(ventas, model);

                JOptionPane.showMessageDialog(null, "Venta ingresada exitosamente");
                //Ventas.MostrarVentas("", 1, Clientes.NumeroPages(""),null,null);
                dispose();
                VentasServicios.MostrarVentaServicios("", 1, VentasServicios.NumeroPages("", null, null), null, null);
            } else {
                JOptionPane.showMessageDialog(null, "No hay detalles para la venta", "Error al guardar",
                        JOptionPane.OK_OPTION);
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed
    // Metodo para hacer visible la ventana de agregar tratammiento
    private void btntratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntratamientoActionPerformed
        ServicoTratamiento servicioManic = new ServicoTratamiento();
        servicioManic.setVisible(true);
        servicioManic.setLocationRelativeTo(null);
    }//GEN-LAST:event_btntratamientoActionPerformed
    // Metodo de cierre del JFRAME
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearVentaServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearVentaServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearVentaServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearVentaServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearVentaServicio().setVisible(true);
            }
        });
    }

    // Genera un número de factura único
    public static String generarNumeroFactura() {
        String ultimoNumero = "00000000"; // Número por defecto si no se encuentra ningún registro en la base de datos
        try {
            // Consulta para obtener el último número de factura
            String consulta = "SELECT MAX(SUBSTRING(numeroFactura, 12, 8)) FROM ventas_servicios";
            ps = conexion.prepareStatement(consulta);
            ResultSet resultSet = ps.executeQuery();
            // Obtener el último número de factura de la base de datos
            if (resultSet.next()) {
                String ultimoNumeroDB = resultSet.getString(1);
                if (ultimoNumeroDB != null) {
                    ultimoNumero = ultimoNumeroDB;
                }
            }
        } catch (SQLException e) {
            e.printStackTrace(); // Imprimir el error en caso de excepción
        }
        // Incrementar el número en 1
        int nuevoNumero = Integer.parseInt(ultimoNumero) + 1;
        String nuevoNumeroStr = String.format("%08d", nuevoNumero); // Formatear el número a 8 dígitos
        // Construir el número de factura con el formato requerido
        return "001-002-00-" + nuevoNumeroStr;
    }

    // Genera un código hexadecimal aleatorio de longitud 32 - Representacion del CAI
    public static String generarCodigoHexadecimal() {
        Random random = new Random(); // Inicializa un objeto Random para generar números aleatorios
        StringBuilder sb = new StringBuilder(); // Inicializa un StringBuilder para construir el código hexadecimal
        // Genera 32 caracteres hexadecimales
        for (int i = 0; i < 32; i++) {
            // Inserta un guión después de cada grupo de 6 caracteres hexadecimales
            if (i > 0 && i % 6 == 0) {
                sb.append('-');
            }
            // Genera un número aleatorio entre 0 y F en hexadecimal
            int valor = random.nextInt(16);
            // Convierte el número a formato hexadecimal y lo agrega al StringBuilder
            String parteHexadecimal = Integer.toHexString(valor);
            sb.append(parteHexadecimal);
        }
        // Devuelve el código hexadecimal en mayúsculas
        return sb.toString().toUpperCase();
    }

    public static void calculos() {
        // Obtiene el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) tblServicio.getModel();
        // Inicializa la variable total
        double total = 0;
        // Recorre todas las filas de la tabla
        for (int i = 0; i < model.getRowCount(); i++) {
            // Obtiene el valor en la columna 2 de la fila actual
            Object object = model.getValueAt(i, 2);
            // Suma el valor al total
            total += Double.parseDouble(object.toString());
        }
        // Muestra el total en el label jlTotal
        jlTotal.setText(String.format("%.2f", total));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnCorte;
    public static javax.swing.JButton btnManicura;
    public static javax.swing.JButton btntratamiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlFecha;
    public static javax.swing.JLabel jlTotal;
    public static javax.swing.JTextField jtClientes;
    public static javax.swing.JTable tblServicio;
    private javax.swing.JLabel txtCai;
    private javax.swing.JLabel txtNumFactura;
    // End of variables declaration//GEN-END:variables
}
