/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import javax.swing.JTextField;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 * Nombre del archivo: MostrarCompras.java 
 * Autor: Nicol Borjas 
 * Fecha de creación: [20/09/2023] 
 * Descripción: Contiene el JFrame con la lista de todos las compras registradas en el sistema. 
 * Derechos de autor (c) [20/09/2023] Nicol Borjas. Todos los derechos reservados.
 */

public class MostrarCompras extends javax.swing.JPanel {
    // Inicialización de la clase MostrarCompras
    private int paginaActual = 1; // Número de página actual
    public static int totalPages = Controlador.ComprasProducto.NumeroPages(); // Número total de páginas

    // Constructor de la clase
    public MostrarCompras() {
        // Inicialización de los componentes de la interfaz gráfica
        initComponents();
        // Desactiva la reordenación de las columnas de la tabla
        tblMostrarCompras.getTableHeader().setReorderingAllowed(false);
        // Muestra las compras en la tabla
        Controlador.ComprasProducto.MostrarCompras("", paginaActual, totalPages);
        // Establece un texto de sugerencia en el campo de búsqueda
        PromptSupport.setPrompt("Buscar por fecha, empresa y número de factura", txtBusqueda);
    } 
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        btnAdelante = new javax.swing.JButton();
        seguimiento = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMostrarCompras = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Listado de Compras");

        txtBusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        txtBusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBusquedaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBusquedaFocusLost(evt);
            }
        });
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(255, 255, 248));
        btnAtras.setForeground(new java.awt.Color(0, 0, 204));
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes proyecto/atras.jpg"))); // NOI18N
        btnAtras.setToolTipText("");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnAdelante.setBackground(new java.awt.Color(255, 255, 248));
        btnAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes proyecto/adelante.jpg"))); // NOI18N
        btnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelanteActionPerformed(evt);
            }
        });

        seguimiento.setText("Pagina: ");

        tblMostrarCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Num.", "Num. De Factura", "CAI", "Empresa", "Tipo de compra", "Fecha", "Total", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMostrarCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMostrarComprasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMostrarCompras);
        if (tblMostrarCompras.getColumnModel().getColumnCount() > 0) {
            tblMostrarCompras.getColumnModel().getColumn(0).setMinWidth(50);
            tblMostrarCompras.getColumnModel().getColumn(0).setMaxWidth(50);
            tblMostrarCompras.getColumnModel().getColumn(6).setResizable(false);
            tblMostrarCompras.getColumnModel().getColumn(7).setMinWidth(0);
            tblMostrarCompras.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        btnNuevo.setBackground(new java.awt.Color(255, 255, 248));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregarN.jpg"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.jpg"))); // NOI18N
        jLabel4.setText("Buscar ");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ListaodologoBarberia (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAtras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdelante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(seguimiento)
                        .addGap(253, 253, 253))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo)
                        .addGap(0, 50, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(27, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnNuevo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAtras)
                            .addComponent(btnAdelante))
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seguimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Método que se ejecuta cuando se suelta una tecla en el campo de búsqueda
    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        // Obtiene el texto ingresado en el campo de búsqueda
        String textoBusqueda = txtBusqueda.getText();
        // Muestra las compras filtradas según el texto de búsqueda y la página actual
        Controlador.ComprasProducto.MostrarCompras(textoBusqueda, paginaActual, totalPages);
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void txtBusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusquedaFocusGained
        // TODO add your handling code here:
        //placeholder para notificar como realizar la busqueda
        JTextField textField = (JTextField) evt.getSource();
        /**String placeholder = "Busqueda por todos los campos excepto total";

        if (textField.getText().equals(placeholder)) {
            textField.setText("");
            textField.setForeground(Color.BLACK); // Establece el color de fuente adecuado
        }
        */
    }//GEN-LAST:event_txtBusquedaFocusGained

    private void txtBusquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBusquedaFocusLost
        // TODO add your handling code here:
        //placeholder para notificar como realizar la busqueda
          JTextField textField = (JTextField) evt.getSource();
          /**String placeholder = "Busqueda por todos los campos excepto total";

          if (textField.getText().isEmpty()) {
            textField.setText(placeholder);
            textField.setForeground(Color.GRAY); // Establece el color de fuente del placeholder
          }
          */
    }//GEN-LAST:event_txtBusquedaFocusLost
    // Método que se ejecuta cuando se presiona el botón de retroceso
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // Verifica si hay páginas anteriores disponibles
        if (paginaActual > 1) {
            // Decrementa el número de página actual
            paginaActual--;
            // Muestra las compras de la página anterior
            Controlador.ComprasProducto.MostrarCompras(txtBusqueda.getText(), paginaActual, totalPages);
        }
    }//GEN-LAST:event_btnAtrasActionPerformed
    // Método que se ejecuta cuando se presiona el botón de avance
    private void btnAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelanteActionPerformed
        // Verifica si hay páginas posteriores disponibles
        if (paginaActual < totalPages) {
            // Incrementa el número de página actual
            paginaActual++;
            // Muestra las compras de la página siguiente
            Controlador.ComprasProducto.MostrarCompras(txtBusqueda.getText(), paginaActual, totalPages);
        }
    }//GEN-LAST:event_btnAdelanteActionPerformed
    
    // Método que se ejecuta cuando se presiona el botón "Nuevo"
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // Crea una nueva ventana para ingresar una compra
        IngresarCompra compras = new IngresarCompra();
        // Hace visible la ventana
        compras.setVisible(true);
        // Centra la ventana en la pantalla
        compras.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnNuevoActionPerformed
    // Método que se ejecuta cuando se hace doble clic en una fila de la tabla de compras   
    private void tblMostrarComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMostrarComprasMouseClicked
        // Verifica si se ha hecho doble clic en la tabla
        if(evt.getClickCount() == 2){
            // Obtiene el índice de la fila seleccionada
            int fila = tblMostrarCompras.getSelectedRow(); 
            // Crea una nueva ventana para mostrar los detalles de la compra
            VerCompras verCompras = new VerCompras(tblMostrarCompras.getValueAt(fila, 0).toString());
            // Actualiza los datos en la ventana de detalles de compra
            verCompras.lblFactura.setText(tblMostrarCompras.getValueAt(fila, 1).toString());
            verCompras.lblCai.setText(tblMostrarCompras.getValueAt(fila, 2).toString());
            verCompras.lblProveedor.setText(tblMostrarCompras.getValueAt(fila, 3).toString());
            verCompras.lblContado.setText(tblMostrarCompras.getValueAt(fila, 4).toString());
            verCompras.lblFecha.setText(tblMostrarCompras.getValueAt(fila, 5).toString());
            // Hace visible la ventana de detalles de compra
            verCompras.setVisible(true);
        }
    }//GEN-LAST:event_tblMostrarComprasMouseClicked

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdelante;
    public static javax.swing.JButton btnAtras;
    public static javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel seguimiento;
    public static javax.swing.JTable tblMostrarCompras;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

}
