/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 * Nombre del archivo: MostrarVentas.java 
 * Autor: Nicol Borjas 
 * Fecha de creación: [20/09/2023] 
 * Descripción: Contiene el JFrame para mostrar todas las opciones que presenta el sistema. 
 * Derechos de autor (c) [20/09/2023] Nicol Borjas. Todos los derechos reservados.
 */
public class Vistaprincipal extends javax.swing.JFrame {

    // Constructor de la clase Vistaprincipal
    public Vistaprincipal() {
        // Inicialización de los componentes
        initComponents();
        // Agregar el panel jPanel1 al contenedor
        add(jPanel1);
        // Establecer el tamaño del contenedor
        content.setSize(1000, 500);
    }

    // Método para identificar una vista y mostrarla en el contenedor
    public void identificarVista(JPanel vista){
        // Establecer el tamaño de la vista
        vista.setSize(1000, 600);
        // Establecer la posición de la vista
        vista.setLocation(0,0);
        // Quitar todos los componentes del contenedor
        content.removeAll();      
        // Agregar la vista al contenedor en el centro
        content.add(vista, BorderLayout.CENTER);
        // Validar y repintar el contenedor para reflejar los cambios
        content.revalidate();
        content.repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        btnCompras = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnTratamientos = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnEmpleados1 = new javax.swing.JButton();
        btnCortes = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnManicuraPedicura = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnInventario1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnVentaServicios = new javax.swing.JButton();
        btnAcercade = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        btnCompras.setBackground(new java.awt.Color(0, 0, 0));
        btnCompras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCompras.setForeground(new java.awt.Color(255, 255, 255));
        btnCompras.setText("COMPRAS");
        btnCompras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51), null, null));
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });

        btnProductos.setBackground(new java.awt.Color(0, 0, 0));
        btnProductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setText("PRODUCTOS");
        btnProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51), null, null));
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnProveedores.setBackground(new java.awt.Color(0, 0, 0));
        btnProveedores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProveedores.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedores.setText("PROVEEDORES");
        btnProveedores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51), null, null));
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });

        btnTratamientos.setBackground(new java.awt.Color(0, 0, 0));
        btnTratamientos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTratamientos.setForeground(new java.awt.Color(255, 255, 255));
        btnTratamientos.setText("TRATAMIENTOS");
        btnTratamientos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51), null, null));
        btnTratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTratamientosActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(0, 0, 0));
        btnClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("CLIENTES");
        btnClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51), null, null));
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnEmpleados1.setBackground(new java.awt.Color(0, 0, 0));
        btnEmpleados1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmpleados1.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleados1.setText("EMPLEADOS");
        btnEmpleados1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51), null, null));
        btnEmpleados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleados1ActionPerformed(evt);
            }
        });

        btnCortes.setBackground(new java.awt.Color(0, 0, 0));
        btnCortes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCortes.setForeground(new java.awt.Color(255, 255, 255));
        btnCortes.setText("CORTES DE CABELLO");
        btnCortes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51), null, null));
        btnCortes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCortesActionPerformed(evt);
            }
        });

        btnInventario.setBackground(new java.awt.Color(0, 0, 0));
        btnInventario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(255, 255, 255));
        btnInventario.setText("INVENTARIO");
        btnInventario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51), null, null));
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        btnManicuraPedicura.setBackground(new java.awt.Color(0, 0, 0));
        btnManicuraPedicura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManicuraPedicura.setForeground(new java.awt.Color(255, 255, 255));
        btnManicuraPedicura.setText("MANICURA Y PEDICURA");
        btnManicuraPedicura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51), null, null));
        btnManicuraPedicura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManicuraPedicuraActionPerformed(evt);
            }
        });

        btnVentas.setBackground(new java.awt.Color(0, 0, 0));
        btnVentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVentas.setText("VENTAS");
        btnVentas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51), null, null));
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("CITAS");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51), null, null));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(1000, 500));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nicol.jpg"))); // NOI18N

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        btnInventario1.setBackground(new java.awt.Color(0, 0, 0));
        btnInventario1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInventario1.setForeground(new java.awt.Color(255, 255, 255));
        btnInventario1.setText("MOBILIARIO");
        btnInventario1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51), null, null));
        btnInventario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventario1ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("DEVOLUCIONES");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51), null, null));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel1.setText("BARBER");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("SALON&SHOPS");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/BIGOTEN.png"))); // NOI18N

        btnInicio.setBackground(new java.awt.Color(0, 0, 0));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("INICIO");
        btnInicio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51), null, null));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnVentaServicios.setBackground(new java.awt.Color(0, 0, 0));
        btnVentaServicios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVentaServicios.setForeground(new java.awt.Color(255, 255, 255));
        btnVentaServicios.setText("VENTAS SERVICIO");
        btnVentaServicios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 51), new java.awt.Color(204, 0, 51), null, null));
        btnVentaServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaServiciosActionPerformed(evt);
            }
        });

        btnAcercade.setBackground(new java.awt.Color(255, 102, 0));
        btnAcercade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAcercade.setText("ACERCA DE");
        btnAcercade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));
        btnAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnVentaServicios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInventario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManicuraPedicura, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(btnInventario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCortes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVentas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEmpleados1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTratamientos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCompras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProveedores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnAcercade, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 1429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(878, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCompras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVentaServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnManicuraPedicura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEmpleados1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInventario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCortes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInventario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAcercade))
                    .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Método para manejar el evento del botón de productos
    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // Crear un menú emergente para las opciones relacionadas con los productos
        JPopupMenu menuCompras = new JPopupMenu();
        // Crear elementos del menú
        JMenuItem submenu = new JMenuItem("                   Crear");
        JMenuItem submenu2 = new JMenuItem("                   Listar");

        // Agregar elementos al menú
        menuCompras.add(submenu);
        menuCompras.add(submenu2);

        // Establecer propiedades del primer submenú
        submenu.setOpaque(true);
        submenu.setBackground(Color.gray);
        submenu.setForeground(Color.white);
        submenu.setHorizontalAlignment(SwingConstants.CENTER);
        submenu.setFont(new java.awt.Font("Segoe UI", 1, 14));

        // Establecer propiedades del segundo submenú
        submenu2.setOpaque(true);
        submenu2.setBackground(Color.gray);
        submenu2.setForeground(Color.white);
        submenu2.setHorizontalAlignment(SwingConstants.CENTER);
        submenu2.setFont(new java.awt.Font("Segoe UI", 1, 14));

        // Establecer el tamaño del menú emergente
        menuCompras.setPopupSize(btnProductos.getWidth(), btnProductos.getPreferredSize().height+50);

        // Agregar acción al primer submenú (Crear)
        submenu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Crear una instancia de la ventana para crear productos
                CrearProductosCuidado crearProductosCuidado = new CrearProductosCuidado();
                // Mostrar la ventana
                crearProductosCuidado.setVisible(true);
            }
        });
        // Agregar acción al segundo submenú (Listar)
        submenu2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Crear una instancia de la ventana para mostrar productos
                MostrarProductosCuidado mostrarProductosCuidado = new MostrarProductosCuidado();
                // Identificar y mostrar la vista correspondiente
                identificarVista(mostrarProductosCuidado);
            }
        });

        // Mostrar el menú emergente en la posición del botón de productos
        menuCompras.show(btnProductos, 0, btnProductos.getHeight());
    }//GEN-LAST:event_btnProductosActionPerformed
    // Método para manejar el evento del botón de proveedores
    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // Crear un menú emergente para las opciones relacionadas con los proveedores
        JPopupMenu menuCompras = new JPopupMenu();
        // Crear elementos del menú
        JMenuItem submenu = new JMenuItem("                   Crear");
        JMenuItem submenu2 = new JMenuItem("                   Listar");

        // Agregar elementos al menú
        menuCompras.add(submenu);
        menuCompras.add(submenu2);

        // Establecer propiedades del primer submenú
        submenu.setOpaque(true);
        submenu.setBackground(Color.gray);
        submenu.setForeground(Color.white);
        submenu.setHorizontalAlignment(SwingConstants.CENTER);
        submenu.setFont(new java.awt.Font("Segoe UI", 1, 14));

        // Establecer propiedades del segundo submenú
        submenu2.setOpaque(true);
        submenu2.setBackground(Color.gray);
        submenu2.setForeground(Color.white);
        submenu2.setHorizontalAlignment(SwingConstants.CENTER);
        submenu2.setFont(new java.awt.Font("Segoe UI", 1, 14));

        // Establecer el tamaño del menú emergente
        menuCompras.setPopupSize(btnProveedores.getWidth(), btnProveedores.getPreferredSize().height+50);

        // Agregar acción al primer submenú (Crear)
        submenu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Crear una instancia de la ventana para crear proveedores
                ProvedoresStore proveedores = new ProvedoresStore();
                // Mostrar la ventana
                proveedores.setVisible(true);
                // Centrar la ventana en la pantalla
                proveedores.setLocationRelativeTo(null);
            }
        });
        // Agregar acción al segundo submenú (Listar)
        submenu2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Crear una instancia de la ventana para mostrar proveedores
                MostrarProveedores provedooor = new MostrarProveedores();
                // Identificar y mostrar la vista correspondiente
                identificarVista(provedooor);
            }
        });

        // Mostrar el menú emergente en la posición del botón de proveedores
        menuCompras.show(btnProveedores, 0, btnProveedores.getHeight());  
    }//GEN-LAST:event_btnProveedoresActionPerformed
    // Método para manejar el evento del botón de inicio
    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // Crear una instancia de la ventana principal
        Vistaprincipal vistaprincipal = new  Vistaprincipal();
        // Mostrar la ventana principal
        vistaprincipal.setVisible(true); 
        // Cerrar la ventana actual
        dispose();
    }//GEN-LAST:event_btnInicioActionPerformed
    // Manejar el evento del botón de compras
    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        // Crear un menú emergente para las opciones de compras
        JPopupMenu menuCompras = new JPopupMenu();
        JMenuItem submenu = new JMenuItem("                   Crear");
        JMenuItem submenu2 = new JMenuItem("                   Listar");

        // Agregar elementos al menú
        menuCompras.add(submenu);
        menuCompras.add(submenu2);

        // Personalizar el estilo de los elementos del menú
        submenu.setOpaque(true);
        submenu.setBackground(Color.gray);
        submenu.setForeground(Color.white);
        submenu.setHorizontalAlignment(SwingConstants.CENTER);
        submenu.setFont(new java.awt.Font("Segoe UI", 1, 14));

        submenu2.setOpaque(true);
        submenu2.setBackground(Color.gray);
        submenu2.setForeground(Color.white);
        submenu2.setHorizontalAlignment(SwingConstants.CENTER);
        submenu2.setFont(new java.awt.Font("Segoe UI", 1, 14));

        // Establecer el tamaño del menú emergente
        menuCompras.setPopupSize(btnCompras.getWidth(), btnCompras.getPreferredSize().height + 50);

        // Agregar acciones a los elementos del menú
        submenu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Abrir la ventana para ingresar una compra
                IngresarCompra ingresarCompra = new IngresarCompra();
                ingresarCompra.setVisible(true);
                ingresarCompra.setLocationRelativeTo(null);
            }
        });
        submenu2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Mostrar la ventana para listar las compras
                MostrarCompras mostrarCompras = new MostrarCompras();
                identificarVista(mostrarCompras);
            }
        });

        // Mostrar el menú emergente en la posición del botón de compras
        menuCompras.show(btnCompras, 0, btnCompras.getHeight());
        
    }//GEN-LAST:event_btnComprasActionPerformed
    // Manejar el evento del botón de clientes
    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // Crear un menú emergente para las opciones de clientes
        JPopupMenu menuCompras = new JPopupMenu();
        JMenuItem submenu = new JMenuItem("                   Crear");
        JMenuItem submenu2 = new JMenuItem("                   Listar");

        // Agregar elementos al menú
        menuCompras.add(submenu);
        menuCompras.add(submenu2);

        // Personalizar el estilo de los elementos del menú
        submenu.setOpaque(true);
        submenu.setBackground(Color.gray);
        submenu.setForeground(Color.white);
        submenu.setHorizontalAlignment(SwingConstants.CENTER);
        submenu.setFont(new java.awt.Font("Segoe UI", 1, 14));

        submenu2.setOpaque(true);
        submenu2.setBackground(Color.gray);
        submenu2.setForeground(Color.white);
        submenu2.setHorizontalAlignment(SwingConstants.CENTER);
        submenu2.setFont(new java.awt.Font("Segoe UI", 1, 14));

        // Establecer el tamaño del menú emergente
        menuCompras.setPopupSize(btnClientes.getWidth(), btnClientes.getPreferredSize().height + 50);

        // Agregar acciones a los elementos del menú
        submenu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Abrir la ventana para crear un nuevo cliente
                CrearCliente crearCliente = new CrearCliente();
                crearCliente.setVisible(true);
            }
        });
        submenu2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Mostrar la ventana para listar los clientes
                MostrarClientes mostrarClientes = new MostrarClientes();
                identificarVista(mostrarClientes);
            }
        });

        // Mostrar el menú emergente en la posición del botón de clientes
        menuCompras.show(btnClientes, 0, btnClientes.getHeight());
    }//GEN-LAST:event_btnClientesActionPerformed
    // Manejar el evento del botón de inventario
    private void btnInventario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventario1ActionPerformed
        // Mostrar la ventana para mostrar el mobiliario y equipo
        MostrarMobiliarioyEquipo mostrarMobiliarioyEquipo = new MostrarMobiliarioyEquipo();
        identificarVista(mostrarMobiliarioyEquipo);
    }//GEN-LAST:event_btnInventario1ActionPerformed
    // Manejar el evento del botón de empleados
    private void btnEmpleados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleados1ActionPerformed
        // Crear un menú emergente para acciones relacionadas con empleados
        JPopupMenu menuCompras = new JPopupMenu();
        JMenuItem submenu = new JMenuItem("                   Crear");
        JMenuItem submenu2 = new JMenuItem("                   Listar");

        // Agregar elementos al menú
        menuCompras.add(submenu);
        menuCompras.add(submenu2);

        // Personalizar la apariencia de los elementos del menú
        submenu.setOpaque(true);
        submenu.setBackground(Color.gray);
        submenu.setForeground(Color.white);
        submenu.setHorizontalAlignment(SwingConstants.CENTER);
        submenu.setFont(new java.awt.Font("Segoe UI", 1, 14));

        submenu2.setOpaque(true);
        submenu2.setBackground(Color.gray);
        submenu2.setForeground(Color.white);
        submenu2.setHorizontalAlignment(SwingConstants.CENTER);
        submenu2.setFont(new java.awt.Font("Segoe UI", 1, 14));

        // Establecer el tamaño del menú emergente
        menuCompras.setPopupSize(btnEmpleados1.getWidth(), btnEmpleados1.getPreferredSize().height + 50);

        // Manejar las acciones de los elementos del menú
        submenu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Mostrar la ventana para crear empleados
                EmpleadosStore empleadosStore = new EmpleadosStore();
                empleadosStore.setVisible(true);
            }
        });
        submenu2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Mostrar la ventana para listar empleados
                MostrarEmpleados mostrarEmpleados = new MostrarEmpleados();
                identificarVista(mostrarEmpleados);
            }
        });

        // Mostrar el menú emergente en la posición del botón de empleados
        menuCompras.show(btnEmpleados1, 0, btnEmpleados1.getHeight());
    }//GEN-LAST:event_btnEmpleados1ActionPerformed
    // Manejar el evento del botón de cortes
    private void btnCortesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCortesActionPerformed
        // Crear un menú emergente para acciones relacionadas con cortes
         JPopupMenu menuCompras = new JPopupMenu();
         JMenuItem submenu = new JMenuItem("                   Crear");
         JMenuItem submenu2 = new JMenuItem("                   Listar");

         // Agregar elementos al menú
         menuCompras.add(submenu);
         menuCompras.add(submenu2);

         // Personalizar la apariencia de los elementos del menú
         submenu.setOpaque(true);
         submenu.setBackground(Color.gray);
         submenu.setForeground(Color.white);
         submenu.setHorizontalAlignment(SwingConstants.CENTER);
         submenu.setFont(new java.awt.Font("Segoe UI", 1, 14));

         submenu2.setOpaque(true);
         submenu2.setBackground(Color.gray);
         submenu2.setForeground(Color.white);
         submenu2.setHorizontalAlignment(SwingConstants.CENTER);
         submenu2.setFont(new java.awt.Font("Segoe UI", 1, 14));

         // Establecer el tamaño del menú emergente
         menuCompras.setPopupSize(btnCortes.getWidth(), btnCortes.getPreferredSize().height + 50);

         // Manejar las acciones de los elementos del menú
         submenu.addActionListener(new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                 // Mostrar la ventana para ingresar un nuevo corte
                 IngresarCorte ingresarCorte = new IngresarCorte();
                 ingresarCorte.setVisible(true);
             }
         });
         submenu2.addActionListener(new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                 // Mostrar la ventana para listar cortes
                 MostrarCortes mostrarCortes = new MostrarCortes();
                 identificarVista(mostrarCortes);
             }
         });

         // Mostrar el menú emergente en la posición del botón de cortes
         menuCompras.show(btnCortes, 0, btnCortes.getHeight());
    }//GEN-LAST:event_btnCortesActionPerformed
    // Manejar el evento del botón de tratamiento
    private void btnTratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTratamientosActionPerformed
        // Crear un menú emergente para acciones relacionadas con tratamientos
        JPopupMenu menuCompras = new JPopupMenu();
        JMenuItem submenu = new JMenuItem("                   Crear");
        JMenuItem submenu2 = new JMenuItem("                   Listar");

        // Agregar elementos al menú
        menuCompras.add(submenu);
        menuCompras.add(submenu2);

        // Personalizar la apariencia de los elementos del menú
        submenu.setOpaque(true);
        submenu.setBackground(Color.gray);
        submenu.setForeground(Color.white);
        submenu.setHorizontalAlignment(SwingConstants.CENTER);
        submenu.setFont(new java.awt.Font("Segoe UI", 1, 14));

        submenu2.setOpaque(true);
        submenu2.setBackground(Color.gray);
        submenu2.setForeground(Color.white);
        submenu2.setHorizontalAlignment(SwingConstants.CENTER);
        submenu2.setFont(new java.awt.Font("Segoe UI", 1, 14));

        // Establecer el tamaño del menú emergente
        menuCompras.setPopupSize(btnTratamientos.getWidth(), btnTratamientos.getPreferredSize().height + 50);

        // Manejar las acciones de los elementos del menú
        submenu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Mostrar la ventana para ingresar un nuevo tratamiento
                IngresarTratamiento ingresarTratamiento = new IngresarTratamiento();
                ingresarTratamiento.setVisible(true);
            }
        });
        submenu2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Mostrar la ventana para listar tratamientos
                MostrarTratamientos mostrarTratamientos = null;
                try {
                    mostrarTratamientos = new MostrarTratamientos();
                } catch (IOException ex) {
                    // Manejar la excepción en caso de error al abrir la ventana
                }
                identificarVista(mostrarTratamientos);
            }
        });

        // Mostrar el menú emergente en la posición del botón de tratamientos
        menuCompras.show(btnTratamientos, 0, btnTratamientos.getHeight());
    }//GEN-LAST:event_btnTratamientosActionPerformed
    // Manejar el evento del botón de manicura y pedicura
    private void btnManicuraPedicuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManicuraPedicuraActionPerformed
        // Crear un menú emergente para acciones relacionadas con manicura y pedicura
        JPopupMenu menuCompras = new JPopupMenu();
        JMenuItem submenu = new JMenuItem("                   Crear");
        JMenuItem submenu2 = new JMenuItem("                   Listar");

        // Agregar elementos al menú
        menuCompras.add(submenu);
        menuCompras.add(submenu2);

        // Personalizar la apariencia de los elementos del menú
        submenu.setOpaque(true);
        submenu.setBackground(Color.gray);
        submenu.setForeground(Color.white);
        submenu.setHorizontalAlignment(SwingConstants.CENTER);
        submenu.setFont(new java.awt.Font("Segoe UI", 1, 14));

        submenu2.setOpaque(true);
        submenu2.setBackground(Color.gray);
        submenu2.setForeground(Color.white);
        submenu2.setHorizontalAlignment(SwingConstants.CENTER);
        submenu2.setFont(new java.awt.Font("Segoe UI", 1, 14));

        // Establecer el tamaño del menú emergente
        menuCompras.setPopupSize(btnManicuraPedicura.getWidth(), btnManicuraPedicura.getPreferredSize().height + 50);

        // Manejar las acciones de los elementos del menú
        submenu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Mostrar la ventana para ingresar una nueva manicura
                IngresarManicura ingresarManicura = new IngresarManicura();
                ingresarManicura.setVisible(true);
            }
        });
        submenu2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Mostrar la ventana para listar manicuras y pedicuras
                Mostrarmanicuraypedicura mostrarmanicuraypedicura = new Mostrarmanicuraypedicura();
                identificarVista(mostrarmanicuraypedicura);
            }
        });

        // Mostrar el menú emergente en la posición del botón de manicura y pedicura
        menuCompras.show(btnManicuraPedicura, 0, btnManicuraPedicura.getHeight());
    }//GEN-LAST:event_btnManicuraPedicuraActionPerformed
    // Manejar el evento del botón de inventario
    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // Crear un menú emergente para listar el inventario
        JPopupMenu menuCompras = new JPopupMenu();
        JMenuItem submenu2 = new JMenuItem("                   Listar");

        // Agregar el elemento al menú
        menuCompras.add(submenu2);

        // Personalizar la apariencia del elemento del menú
        submenu2.setOpaque(true);
        submenu2.setBackground(Color.gray);
        submenu2.setForeground(Color.white);
        submenu2.setHorizontalAlignment(SwingConstants.CENTER);
        submenu2.setFont(new java.awt.Font("Segoe UI", 1, 14));

        // Establecer el tamaño del menú emergente
        menuCompras.setPopupSize(btnInventario.getWidth(), btnInventario.getPreferredSize().height + 50);

        // Manejar la acción del elemento del menú
        submenu2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Mostrar la ventana para listar el inventario
                MostrarInventario mostrarinventario = new MostrarInventario();
                identificarVista(mostrarinventario);
            }
        });

        // Mostrar el menú emergente en la posición del botón de inventario
        menuCompras.show(btnInventario, 0, btnInventario.getHeight());
    }//GEN-LAST:event_btnInventarioActionPerformed
    // Manejar el evento del botón de ventas
    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // Crear un menú emergente para opciones de ventas
        JPopupMenu menuCompras = new JPopupMenu();
        JMenuItem submenu = new JMenuItem("                   Crear");
        JMenuItem submenu2 = new JMenuItem("                   Listar");

        // Agregar elementos al menú
        menuCompras.add(submenu);
        menuCompras.add(submenu2);

        // Personalizar la apariencia del primer elemento del menú
        submenu.setOpaque(true);
        submenu.setBackground(Color.gray);
        submenu.setForeground(Color.white);
        submenu.setHorizontalAlignment(SwingConstants.CENTER);
        submenu.setFont(new java.awt.Font("Segoe UI", 1, 14));

        // Personalizar la apariencia del segundo elemento del menú
        submenu2.setOpaque(true);
        submenu2.setBackground(Color.gray);
        submenu2.setForeground(Color.white);
        submenu2.setHorizontalAlignment(SwingConstants.CENTER);
        submenu2.setFont(new java.awt.Font("Segoe UI", 1, 14));

        // Establecer el tamaño del menú emergente
        menuCompras.setPopupSize(btnVentas.getWidth(), btnVentas.getPreferredSize().height + 50);

        // Manejar la acción del primer elemento del menú (Crear)
        submenu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Mostrar la ventana para crear ventas
                CrearVentas crearVentas = new CrearVentas();
                crearVentas.setVisible(true);
            }
        });

        // Manejar la acción del segundo elemento del menú (Listar)
        submenu2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Mostrar la ventana para listar ventas
                MostrarVentas mostrarVentas = new MostrarVentas();
                identificarVista(mostrarVentas);
            }
        });

        // Mostrar el menú emergente en la posición del botón de ventas
        menuCompras.show(btnVentas, 0, btnVentas.getHeight());
    }//GEN-LAST:event_btnVentasActionPerformed
    // Manejar el evento del botón jButton8
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Crear un menú emergente para opciones de citas
         JPopupMenu menuCompras = new JPopupMenu();
         JMenuItem submenu = new JMenuItem("                   Crear");
         JMenuItem submenu2 = new JMenuItem("                   Listar");

         // Agregar elementos al menú
         menuCompras.add(submenu);
         menuCompras.add(submenu2);

         // Personalizar la apariencia del primer elemento del menú
         submenu.setOpaque(true);
         submenu.setBackground(Color.gray);
         submenu.setForeground(Color.white);
         submenu.setHorizontalAlignment(SwingConstants.CENTER);
         submenu.setFont(new java.awt.Font("Segoe UI", 1, 14));

         // Personalizar la apariencia del segundo elemento del menú
         submenu2.setOpaque(true);
         submenu2.setBackground(Color.gray);
         submenu2.setForeground(Color.white);
         submenu2.setHorizontalAlignment(SwingConstants.CENTER);
         submenu2.setFont(new java.awt.Font("Segoe UI", 1, 14));

         // Establecer el tamaño del menú emergente
         menuCompras.setPopupSize(jButton8.getWidth(), jButton8.getPreferredSize().height + 50);

         // Manejar la acción del primer elemento del menú (Crear)
         submenu.addActionListener(new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                 // Mostrar la ventana para ingresar una nueva cita
                 IngresarCita ingresarCita = new IngresarCita();
                 ingresarCita.setVisible(true);
             }
         });

         // Manejar la acción del segundo elemento del menú (Listar)
         submenu2.addActionListener(new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                 // Mostrar la ventana para listar citas
                 MostrarCitas citaas = new MostrarCitas();
                 identificarVista(citaas);
             }
         });

         // Mostrar el menú emergente en la posición del botón jButton8
         menuCompras.show(jButton8, 0, jButton8.getHeight());
    }//GEN-LAST:event_jButton8ActionPerformed
    // Manejar el evento del botón btnVentaServicios
    private void btnVentaServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaServiciosActionPerformed
        // Crear un menú emergente para opciones de venta de servicios
        JPopupMenu menuCompras = new JPopupMenu();
        JMenuItem submenu = new JMenuItem("                   Crear");
        JMenuItem submenu2 = new JMenuItem("                   Listar");

        // Agregar elementos al menú
        menuCompras.add(submenu);
        menuCompras.add(submenu2);

        // Personalizar la apariencia del primer elemento del menú
        submenu.setOpaque(true);
        submenu.setBackground(Color.gray);
        submenu.setForeground(Color.white);
        submenu.setHorizontalAlignment(SwingConstants.CENTER);
        submenu.setFont(new java.awt.Font("Segoe UI", 1, 14));

        // Personalizar la apariencia del segundo elemento del menú
        submenu2.setOpaque(true);
        submenu2.setBackground(Color.gray);
        submenu2.setForeground(Color.white);
        submenu2.setHorizontalAlignment(SwingConstants.CENTER);
        submenu2.setFont(new java.awt.Font("Segoe UI", 1, 14));

        // Establecer el tamaño del menú emergente
        menuCompras.setPopupSize(btnVentaServicios.getWidth(), btnVentaServicios.getPreferredSize().height + 50);

        // Manejar la acción del primer elemento del menú (Crear)
        submenu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Mostrar la ventana para crear una nueva venta de servicio
                CrearVentaServicio crearVentaServicio = new CrearVentaServicio();
                crearVentaServicio.setVisible(true);
                crearVentaServicio.setLocationRelativeTo(null);
            }
        });

        // Manejar la acción del segundo elemento del menú (Listar)
        submenu2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Mostrar la ventana para listar ventas de servicios
                MostrarVentaServicios mostrarVentaServicios = new MostrarVentaServicios();
                identificarVista(mostrarVentaServicios);
            }
        });

        // Mostrar el menú emergente en la posición del botón btnVentaServicios
        menuCompras.show(btnVentaServicios, 0, btnVentaServicios.getHeight());
    }//GEN-LAST:event_btnVentaServiciosActionPerformed
    // Manejar el evento del botón jButton6
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Crear una instancia de la ventana para mostrar devoluciones
        MostrarDevoluciones mostrarDevoluciones = new MostrarDevoluciones();

        // Utilizar el método identificarVista para mostrar la ventana en la interfaz principal
        identificarVista(mostrarDevoluciones);
    }//GEN-LAST:event_jButton6ActionPerformed
    // Manejar el evento del botón btnAcercade
    private void btnAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercadeActionPerformed
        // Crear una instancia de la ventana Acerca_DEe
        Acerca_DEe acerca = new Acerca_DEe();
        // Utilizar el método identificarVista para mostrar la ventana en la interfaz principal
        identificarVista(acerca);
    }//GEN-LAST:event_btnAcercadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vistaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vistaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vistaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vistaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vistaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcercade;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnCortes;
    private javax.swing.JButton btnEmpleados1;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnInventario1;
    private javax.swing.JButton btnManicuraPedicura;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnTratamientos;
    private javax.swing.JButton btnVentaServicios;
    private javax.swing.JButton btnVentas;
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
